services:
  redis-backup:
    build:
      context: .
      dockerfile: Dockerfile

    # Keep container running
    stdin_open: true
    tty: true

  local-redis:
    image: redis:latest
    restart: always
    ports:
      - "6380:6379"
    command: redis-server /usr/local/etc/redis/redis.conf --save 60 1 --requirepass yoyo
    volumes:
      - ./local-redis-data/redis.conf:/usr/local/etc/redis/redis.conf
      - ./local-redis-data:/data

  test-redis:
    image: redis:latest
    restart: always
    ports:
      - "6381:6379"
    command: redis-server --save 60 1 --requirepass yoyo
    volumes:
      - ./test-redis-data:/data
